### ISSUE TITLE
ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by ignization** [atahanuz/lol-stats#1]
Böyle bir hata alıyorum anaconda spyder üzerinden yürütmeye çalıştığımda neden olduğu hakkında çok araştırdım ama bulamadım yardımcı olabilir misin

**Comment by ignization** [comment]
Traceback (most recent call last):
  File "C:\Users\pc\anaconda3\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\anaconda3\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\anaconda3\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\anaconda3\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\anaconda3\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\anaconda3\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\pc\.spyder-py3\lol-stats-master\main.py", line 72, in index
    df = run(links,flag)
         ^^^^^^^^^^^^^^^
  File "c:\users\pc\.spyder-py3\lol-stats-master\main.py", line 122, in run
    return merger(list(tables_list),flag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\pc\.spyder-py3\lol-stats-master\main.py", line 262, in merger
    merged = pd.concat(tables_list)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\anaconda3\Lib\site-packages\pandas\core\reshape\concat.py", line 372, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "C:\Users\pc\anaconda3\Lib\site-packages\pandas\core\reshape\concat.py", line 429, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by atahanuz** [comment]
Merhaba, bu projeyi yeniden tasarlıyorum. Kısa süre içinde tekrar yayınlayacağım
Hi, I'm redesigning the project. I'll re-release it soon.

**Comment by atahanuz** [comment]
> Traceback (most recent call last): File "C:\Users\pc\anaconda3\Lib\site-packages\flask\app.py", line 2091, in **call** return self.wsgi_app(environ, start_response) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\pc\anaconda3\Lib\site-packages\flask\app.py", line 2076, in wsgi_app response = self.handle_exception(e) ^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\pc\anaconda3\Lib\site-packages\flask\app.py", line 2073, in wsgi_app response = self.full_dispatch_request() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\pc\anaconda3\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request rv = self.handle_user_exception(e) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\pc\anaconda3\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request rv = self.dispatch_request() ^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\pc\anaconda3\Lib\site-packages\flask\app.py", line 1503, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\users\pc.spyder-py3\lol-stats-master\main.py", line 72, in index df = run(links,flag) ^^^^^^^^^^^^^^^ File "c:\users\pc.spyder-py3\lol-stats-master\main.py", line 122, in run return merger(list(tables_list),flag) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\users\pc.spyder-py3\lol-stats-master\main.py", line 262, in merger merged = pd.concat(tables_list) ^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\pc\anaconda3\Lib\site-packages\pandas\core\reshape\concat.py", line 372, in concat op = _Concatenator( ^^^^^^^^^^^^^^ File "C:\Users\pc\anaconda3\Lib\site-packages\pandas\core\reshape\concat.py", line 429, in **init** raise ValueError("No objects to concatenate") ValueError: No objects to concatenate

Merhaba, projeyi yeniden tasarladım. Tekrar deneyip geri bildirim verirsen mutlu olurum.

I redesigned the project, not is can be installed by PIP. The program now automatically manages ChromeDriver installation.
